// List of every localization key the UI consumes. Used by the dev debugger
// and by the "Copy Headers" Developer Tool in Settings.
export const REQUIRED_LOCALIZATION_KEYS = [
  "nav_home",
  "nav_about",
  "nav_settings",
  "hero_title",
  "hero_subtitle",
  "search_placeholder",
  "filter_all",
  "filter_released",
  "filter_ongoing",
  "sort_label",
  "sort_title",
  "sort_progress",
  "sort_status",
  "play_now",
  "share",
  "copy_link",
  "link_copied",
  "progress",
  "refresh_data",
  "loading",
  "no_games",
  "fetch_error",
  "offline",
  "refresh_success",
  "appearance",
  "language",
  "about",
  "theme_dark",
  "theme_light",
  "about_arsepat",
  "footer_tagline",
  "install_title",
  "install_body",
  "install_yes",
  "install_later",
  "install_done",
  "offline_banner",
  "empty_title",
  "empty_body",
  "pull_to_refresh",
  "release_to_refresh",
  "developer_tools",
  "copy_headers_games",
  "copy_headers_localization",
  "copy_headers_metadata",
  "headers_copied",
];

export const SHEET_HEADERS = {
  games: [
    "id",
    "title",
    "description",
    "status",
    "play_url",
    "image_url",
    "progress_percent",
    "genre",
    "tags",
  ],
  localization: ["key", "id_text", "en_text"],
  metadata: ["setting_key", "setting_value"],
};

// Recommended metadata keys (for the Copy Headers tool — pasted as a second row).
export const METADATA_KEYS = [
  "site_title",
  "site_meta_description",
  "hero_badge",
  "hero_title",
  "hero_tagline",
  "about_text",
  "footer_tagline",
  "announcement",
  "app_logo_url",
  "app_icon_url",
  "og_image_url",
  "og_image_id_url",
  "og_image_en_url",
  "social_twitter",
  "social_twitter_enabled",
  "social_instagram",
  "social_instagram_enabled",
  "social_github",
  "social_github_enabled",
  "social_website",
  "social_website_enabled",
  "announcement",
  "announcement_enabled",
  // Badge styling (dynamic via sheet)
  "badge_shape", // "pill" | "rounded" | "square"
  "tag_max", // integer, max tags shown on card
  "genre_bg",
  "genre_fg",
  "tag_bg",
  "tag_fg",
  "tag_border",
];
